services:
- type: web
  name: File Organizer 2000
  runtime: node
  rootDir: ./packages/web  
  buildCommand: pnpm install; pnpm run build:self-host
  startCommand: pnpm start
  autoDeploy: true
  envVars:
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    sync: false
  - key: SOLO_API_KEY
    sync: false
