/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OrUkkdrIudr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="max-w-6xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
      <div className="grid gap-6">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight">File Changes Preview</h1>
          <p className="mt-2 text-gray-500 dark:text-gray-400">
            Review the proposed changes to your files before committing.
          </p>
          <div className="flex justify-end mt-4 gap-2">
            <Button>Apply All Changes</Button>
          </div>
        </div>
        <div className="grid gap-4">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-4">
                <FileIcon className="w-8 h-8" />
                <div className="grid gap-1">
                  <CardTitle>index.js → index.js</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500 dark:text-gray-400">Previous location:</span>
                      <span>src/components</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500 dark:text-gray-400">New location:</span>
                      <span>src/pages</span>
                    </div>
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex justify-end mt-4">
                <Button>Apply Changes</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <div className="flex items-center gap-4">
                <FileIcon className="w-8 h-8" />
                <div className="grid gap-1">
                  <CardTitle>styles.css → styles.css</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500 dark:text-gray-400">Previous location:</span>
                      <span>src/styles</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500 dark:text-gray-400">New location:</span>
                      <span>src/assets/css</span>
                    </div>
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex justify-end mt-4">
                <Button>Apply Changes</Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <div className="flex items-center gap-4">
                <FileIcon className="w-8 h-8" />
                <div className="grid gap-1">
                  <CardTitle>utils.js → utils.js</CardTitle>
                  <CardDescription>
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500 dark:text-gray-400">Previous location:</span>
                      <span>src/utils</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-gray-500 dark:text-gray-400">New location:</span>
                      <span>src/helpers</span>
                    </div>
                  </CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex justify-end mt-4">
                <Button>Apply Changes</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}
